version: '3.8'
services:
  dev-db:
    image: postgres:13
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: blubbio-db
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: blubbio
    networks:
      - blubbio
networks:
  blubbio: